### ISSUE TITLE
Монохромный режим отображения

### ISSUE THREAD

**Issue by 4113556** [SR3u/gphotorepo#1]
Добавить возможность выбирать монохромный режим отображения (как на старых Macintosh).
Ключем запуска приложения, параметром из конфига, хоткеем или из графического интерфейса. Смотря, как удобнее это реализовать. Главное выделить это, как независимый модуль-фитчу, чтобы использовать независимо от других параметров клиента.

**Comment by SR3u** [comment]
Depends on https://github.com/SR3u/gphotorepo/issues/2

**Comment by SR3u** [comment]
Resolved in https://github.com/SR3u/gphotorepo/issues/2
