### ISSUE TITLE
Выбор альбома

### ISSUE THREAD

**Issue by 4113556** [SR3u/gphotorepo#4]
Добавить возможность выбирать отдельный альбом в Google Photo. Тип реализации не имеет значения.

**Comment by SR3u** [comment]
Resolve proposed in https://github.com/SR3u/gphotorepo/commit/2ae2fd704c56a6b375a637b134c6b4a96c99e72d

**Comment by SR3u** [comment]
Resolved in https://github.com/SR3u/gphotorepo/commit/352e9f82a2b4aa280df49513b371e20704212320
